// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twnvzivwlcdolymimlcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3bnZ6aXZ3bGNkb2x5bWltbGNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjYwODcsImV4cCI6MjA3MzQ0MjA4N30.DbvaX91_u6czVkct5fSAIbwG6wy0QnEoyI1NEBL0lSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});